name: Create a Pull Request for a Release Branch

on:
    workflow_dispatch:
    push:
        branches:
            - release/*

jobs:
    create_pr:
        runs_on: ubuntu-latest
        steps:
            #Checkout the repositiry
            - name: Ceckout the repository
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            # Create a pull request (if one already doesn't exist)
            - name: Creat Pull Request
              run: |
                pr_list=$(gh pr list --base "$GITHUB_BASE_REF" --json number --jq '.[] | .number')
                if [ -n "$pr_list" ]; then  
                    echo "Pull request for branch $GITHUB_BASE_REF already exists." 
                else  
                    gh pr create --fill --draft --base live   
                fi
                
              env:
                GITHUB_TOKEN: ${{ github.token}}

